#!/usr/bin/perl
# Written by Dominik Woltanski <minikwolt@astri.umk.pl> October 1, 2008
my $argc = $#ARGV+1;
if($argc < 1){
   print "USAGE: newcompiler <compset>\n";
   print "If you need a non-standard compiler, please, add a new file\n";
   print "into 'compilers' directory, that contains environment you need.\n";
   print "The name of that file should be '<compset>.in', where <compset> is\n";
   print "a part of this name, that you want to use while changing the compiler.\n";
   print "Available compilers are:\n";
   print " \n";
   system("cd ../compilers && ls *.in && cd ../obj");
   print " \n";
} else {
$compdir = "../compilers/". $ARGV[0] . ".in";
if(!-r $compdir) { 
print "Available compilers are:\n";
system("cd ../compilers && ls *.in && cd ../obj");
die "\n $compdir does not exist! ";
}
open MAKEIN, $compdir or die $!;
@makein = <MAKEIN>;
close MAKEIN;
open MAKEPREP, "< Makefile-prep" or die $!;
@makeprep = <MAKEPREP>;
close MAKEPREP;

open(MAKEFILE, "> Makefile");
print MAKEFILE @makein;
print MAKEFILE @makeprep;
close MAKEFILE;

}
